[package]
name = "iced-test"
version = "0.1.0"
edition = "2024"

[dependencies]
iced_widget = "0.13.4"
# iced_tiny_skia = { version = "0.13.0" }
# iced = {version="*", features=["advanced", "image"]}
tracing-subscriber = { version = "0.3.19", default-features = false, features = ["fmt"] }
iced_renderer = { version = "0.13.0", features = ["tiny-skia"] }
iced_tiny_skia = "0.13.0"
raw-window-handle = { version = "0.6.2", features = ["std"] }
anyhow = "1.0.98"

[target.'cfg(target_os = "linux")'.dependencies]
xcb = { version = "1.5.0", features = ["dri3"] }
memmap2 = "0.9.5"

# [patch.crates-io]
# softbuffer = { path = "../id/softbuffer" }

# [patch.'