[package]
name = "iced-test"
version = "0.1.0"
edition = "2024"

[dependencies]
iced_widget = { version = "0.13.4", features = ["image"] }
tracing-subscriber = { version = "0.3.19", default-features = false, features = ["fmt"] }
iced_renderer = { version = "0.13.0", features = ["image", "tiny-skia"] }
iced_tiny_skia = { version = "0.13.0", features = ["image"] }
raw-window-handle = { version = "0.6.2", features = ["std"] }
anyhow = "1.0.98"
iced_graphics = { version = "0.13.0", features = ["image"] }
iced_core = "0.13.2"
iced_runtime = "0.13.2"

[target.'cfg(target_os = "linux")'.dependencies]
winit = "0.30.9"
