[package]
edition = "2024"
name = "iced-test"
version = "0.1.0"

[dependencies]
anyhow = "1.0.98"
iced_renderer = {version = "0.13", features = ["image", "tiny-skia"]}
iced_runtime = "0.13"
iced_tiny_skia = {version = "0.13", features = ["image"]}
iced_widget = {version = "0.13", features = ["image"]}
image = "0.24.9"
tracing-subscriber = {version = "0.3.19", default-features = false, features = ["fmt"]}

[target.'cfg(target_os = "linux")'.dependencies]
winit = "0.30.9"
